### PR TITLE
Add missing empty column to overrides

### PR DESCRIPTION
**Pull request by bgyori**
This fixes an issue in which the third column of the overrides table (which is always blank) was left out in some of the overrides. This was the reason behind https://github.com/clulab/reach/issues/671, and I confirmed locally that this PR fixes that. It makes me wonder if the failed tests in my comment here: https://github.com/clulab/bioresources/pull/27#issuecomment-609459815 were actually failing because of this issue and we shouldn't have change the tests.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks!

I think those tests in #27 were failing for legitimate reasons, where the labels were correctly changed to other things. 

I'll rerun the reach tests again, and if everything passes, release a new version of bioresources.

**Comment by MihaiSurdeanu** [comment]
@bgyori: Wait. I see the changed python script, but not the modified KB files. Can you please commit those too here?

**Comment by bgyori** [comment]
The updated NER-Grounding-Override.tsv.gz was part of this PR and It looks to me like it has the intended change in it when decompressed.

**Comment by MihaiSurdeanu** [comment]
You're right. Sorry about my confusion.

**Comment by MihaiSurdeanu** [comment]
@bgyori: can you please check if these groundings are Ok:

```
MENTION TEXT:  Neuregulin
LABELS:        List(Family, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)
DISPLAY LABEL: Family
	------------------------------
	RULE => ner-family-entities
	TYPE => CorefTextBoundMention
	------------------------------
	GROUNDING: <KBResolution: Neuregulin, fplx, NRG, human, <IMKBMetaInfo: uaz, NER-Grounding-Override.tsv.gz, , , sp=false, f=false, p=false>>

CONTEXT: NONE
	------------------------------



MENTION TEXT:  Neuroregulin
LABELS:        List(Family, Equivalable, BioChemicalEntity, BioEntity, Entity, PossibleController)
DISPLAY LABEL: Family
	------------------------------
	RULE => ner-family-entities
	TYPE => CorefTextBoundMention
	------------------------------
	GROUNDING: <KBResolution: neuregulin, pfam, PF02158, human, <IMKBMetaInfo: uaz, NER-Grounding-Override.tsv.gz, , , sp=false, f=false, p=false>>

CONTEXT: NONE
```

**Comment by MihaiSurdeanu** [comment]
Previously, they were both grounded to `PF02158`. Now Neuregulin is grounded to `NRG`.

**Comment by MihaiSurdeanu** [comment]
Similarly, "NOTCH" used to be grounded to `PF00066`, and now it is `Notch`.

**Comment by MihaiSurdeanu** [comment]
Similarly,
- "IRS" used to be `PF02174`. Now it is `IRS`.
- "IGFBP" used to be `PF00219`. Now it is `IGFBP`.
- "HSP90" used to be `PF00183`. Now it is `HSP90`.
- "GATA" used to be `PF00320`. Now it is `GATA`.
- "FGF" used to be `PF00167`. Now it is `FGF`.
- "ETS" used to be `PF00178`. Now it is `ETS`.
- "DVL" used to be `PF08137`. Now it is `DVL`.
- "COX8" used to be `PF02285`. Now it is `COX8`.
- "COX7b" used to be `PF05392`. Now it is `COX7B`.
- "COX7a" used to be `PF02238`. Now it is `COX7A`.
- "COX6b" used to be `PF02297`. Now it is `COX6B`.
- "COX6a" used to be `PF02046`. Now it is `COX6A`.
- "COX4" used to be `PF02936`. Now it is `COX4`.
- "CRISP" used to be `PF08562`. Now it is `CRISP`.
- "Cadherin" used to be `PF00028`. Now it is `Cadherin`.

**Comment by bgyori** [comment]
All of the groundings you listed are correct now in prioritizing FamPlex over Pfam. The only one that is not intended to be this way is the Neuregulin/Neuroregulin distinction. I added another synonym to FamPlex to solve that but I will have to take another look tomorrow before PR-ing that into bioresources.

**Comment by MihaiSurdeanu** [comment]
Ok, thanks!
I'll wait to release bioresources then.

**Comment by MihaiSurdeanu** [comment]
I've adjusted these unit tests in the Reach branch "bio31". I'm waiting on your PR, before I merge the Reach branch into master.

**Comment by bgyori** [comment]
Thanks! I am looking at it and need a little bit more time to make sense of things. It appears there are many old entries in the overrides file (that were there before my recent PRs and I didn't modify) that overlap with entries from FamPlex, so, for consistency, should be modified to map to FamPlex. Neuregulin is one such example, where inconsistent overrides result in two synonyms mapping to two different namespaces.

**Comment by bgyori** [comment]
Sigh... as I'm working my way through the overrides file, I found a bunch of issues, including that all the HMDB mappings are to outdated IDs and some GO mappings that are either to outdated IDs or not the right entries to map to. I feel like it's worth taking care of these now, but it will take more time.

**Comment by MihaiSurdeanu** [comment]
Ok. Thanks for the update!

**Pull request merged**
