### PR TITLE
Import more SARS-CoV-2 synonyms

### PR DESCRIPTION
**Pull request by bgyori**
This PR imports more synonyms for SARS-CoV-2 proteins that are missing from UniProt. The synonyms are gathered from this publication: https://www.nature.com/articles/s41586-020-2286-9. Note that these aren't overrides, they are just extensions for NER and grounding as additional choices.

### CODE REVIEW

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by kwalcock** [comment]
Is this worth republishing while I'm still at it?  Reach could skip to this version.

**Comment by MihaiSurdeanu** [comment]
Yes please.

**Comment by kwalcock** [comment]
This has been published to maven.

**Comment by bgyori** [comment]
Thanks! It's likely that I will make further improvements in the coming days as I'm evaluating performance - for our purposes it's not a problem if a version isn't released (because we can build custom versions locally) so it's fully up to you when you want to do releases, given that it comes with some overhead.

**Pull request merged**
