### PR TITLE
Improvements to protein synonyms/NER

### PR DESCRIPTION
**Pull request by bgyori**
This PR makes the following changes:
- Add a note about NER and organisms to the README (see #50)
- Update the list of synonyms from UniProt
- Remove single-letter protein synonyms from uniprot-proteins and the corresponding NER file
(Note that most NER files other than Gene_or_gene_product.tsv.gz are effectively unchanged, though they show up in the diff)

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks @bgyori! 
Can you please add a summary of this PR to the CHANGES file?

**Comment by MihaiSurdeanu** [comment]
@kwalcock: this is a significant PR. Can you please release it, and update Reach (assuming tests pass)?

**Comment by bgyori** [comment]
@MihaiSurdeanu thanks, I added a line to CHANGES in #52. I agree that releasing this would be good, though there aren't huge changes to the default resource files, my 2 PRs today are mostly to support local custom builds.

**Comment by MihaiSurdeanu** [comment]
Thanks! Merged.

**Comment by kwalcock** [comment]
Yes.  Hopefully the other recent reach and possibly processor changes can be coordinated with this.  There's a reach PR now.  It looks like @bgyori updated the files in the ner directory before the first merge into master.  Can I assume that the second merge into master does not require an update to those files?

**Comment by MihaiSurdeanu** [comment]
I think that's correct.

**Comment by kwalcock** [comment]
The tests passed with reach, both the master branch of reach and the one with forthcoming fixes.  I'll try to get this published then.

**Comment by MihaiSurdeanu** [comment]
Thank you!

**Pull request merged**
