### PR TITLE
Add MeSH diseases

### PR DESCRIPTION
**Pull request by bgyori**
This PR adds a script to generate a mesh-disease.tsv file with all the names and synonyms of the entries in the MeSH disease subtree. I introduced a new entity type called `Disease` for these. The corresponding changes and testing in Reach is still in progress so I suggest waiting with the merge before those are sorted out.

### CODE REVIEW

**Comment by bgyori** [comment]
@MihaiSurdeanu I'm happy with this now and all Reach tests are passing as far as I can tell.

**Comment by MihaiSurdeanu** [comment]
Thanks!

It seems some files have been changed in this PR that should not have been. For example, BioProcess, Species, and TissueType have been modified (did not do a diff yet). Do you know why?

**Comment by bgyori** [comment]
I made some actual changes in BioProcess to remove some terms that were tagged as biological processes but are actually diseases from MeSH (since these are now included in the new mesh-diseases file). The other files haven't actually changed, it's just that ner_kb.sh regenerates all the files by default, even if they haven't meaningfully changed.

**Comment by MihaiSurdeanu** [comment]
Cool. Thanks!

**Pull request merged**
